### ISSUE TITLE
input控件掉帧严重

### ISSUE THREAD

**Issue by Vjze** [syf20020816/SurrealismUI#3]
RT，不知道视频能不能看出来。
https://github.com/syf20020816/SurrealismUI/assets/99671889/83af7ba6-648b-472d-af76-7eee25aeb912

https://github.com/syf20020816/SurrealismUI/assets/99671889/3713a891-54c9-490b-97f4-11214edb2c2c

**Comment by syf20020816** [comment]
经过测试当前并未发现延时或掉帧问题
